services:
  frontend:
    image: frontend
    container_name: church-frontend
    working_dir: /app/
    entrypoint: npm start #tail -f /dev/null #
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - church_network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: church_user
      POSTGRES_PASSWORD: church_password
      POSTGRES_DB: church_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - church_network

networks:
  church_network:
    driver: bridge

volumes:
  db_data: