services:
  frontend:
    image: frontend
    container_name: church-frontend
    working_dir: /app/
    entrypoint: npm start #tail -f /dev/null #
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
