services:
  frontend:
    image: frontend
    working_dir: /app/
    entrypoint: npm start #tail -f /dev/null #
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - network
    
  backend:
    build:
      context: backend
    environment:
      - DATABASE_URL=postgresql://user:pwd@db:5432/puzzle_db
    depends_on:
      - db
    networks:
      - network
    volumes:
      - ./backend/flask:/flask
    entrypoint: tail -f /dev/null && python3 /flask/app.py

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: puzzle_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  db_data: