version: "3.3"

services:
  frontend:
    image: frontend
    container_name: church-frontend
    working_dir: /app/
    entrypoint: npm start #tail -f /dev/null #
    build:
      context: ./frontend
    networks:
      church_network:
        ipv4_address: 172.16.1.11
    ports:
      - "3000:3000"
